### PR TITLE
Gdd/create and install the base front end

### PR DESCRIPTION
**Pull request by godDeveloppeur**
# Description

Completed issue list : #81 , #82 , #83 , #84 

Here is the list of things that were done : 

- [x] Creation of the basic FrontEnd (I have the old frontend in oldFrontEnd)
- [x] Creation of almost all react components with their html and scss
- [x] Added navigation with top buttons
- [x] The dates component shares the same information across all pages
- [x] Creation of a data context to have access to date and repository information on all pages
- [x] Added bubble chart, Adding slider filters
- [x] Added the metrics presentation component (Just the interface, missing the logic for this one)
- [x] Added and updated documentation
- [x] Added motion chart graph for visualizing file history across commits
- [x] Generating fake data for testing
- [x] Added back button to home page

### CODE REVIEW

**Review by zergov — COMMENTED** [review]
Yooo 👋 I didn't review yet, I'll do this probably sunday or monday. One thing I can say without even looking at the code is: can we just 🔥 the old frontend instead of moving it? 

I'll do the same for the old backend.

**Comment by godDeveloppeur** [comment]
To respond to your comment : https://github.com/visevol/Cscope/pull/85#pullrequestreview-2411796309

If we created a new repository, I wouldn't mind excluding their thing. But the problem is that we are in the same repository, so if we delete this, it will be permanent. I would like us to ask the teacher first if it's ok. if he is not going to want to use the old version for something else or for example just to rate us by making a comparison

**Comment by zergov** [comment]
> we created a new repository, I wouldn't mind excluding their thing. But the problem is that we are in the same repository, so if we delete this, it will be permanent.

Nah it's not permanent, it's in the Git repository's history forever. You can always go back and re-add these files in the future. 

Right now it just polutes the repository.

**Comment by godDeveloppeur** [comment]
> Nah it's not permanent, it's in the Git repository's history forever. You can always go back and re-add these files in the future.
> 
> Right now it just polutes the repository.

Oh that's right, you're right. So yes, then we can delete the old files

**Review by zergov — APPROVED** [review]
Awesome work man! 

Honestly, it's a very nice base. It's going to be easy to iterate on this without walking on each other's foot. It also looks quite nice, good stuff :D 

Everything is nicely separated, layout and pages are in their own directory, and the am5 components are abstracted in their own component. 

Ship it 🚢

**Pull request merged**
